# Site

title: Geospatial Packages in R
handouts:
 - worksheet.R
 - data/cb_2016_us_county_5m
 - data/huc250k
 - data/nlcd_agg.grd
 - data/nlcd_agg.gri
 - data/README.md
tag: v0.3
lesson: 9
instructor: Beno√Æt Parmentier
authors:
  - Philippe Marchand
  - Ian Carroll

# Slides

slide_sorter:
  - intro
  - vector
  - raster
  - extract
  - refs
  - solutions

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.3/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
