# Site

title:
handouts:
tag:
lesson:
instructor:
authors:

# Slides

slide_sorter:

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.3/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

github: [metadata]
markdown: kramdown
collections:
  - slides
